apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels: {}
  template:
    metadata:
      labels: {}
    spec:
      containers:
        - name: backend
          image: ghcr.io/sysadmin29/back-end:latest
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: backend-config
            - secretRef:
                name: backend-secrets